
package messageboard.client.jaxws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MessageBoardSOAPService", targetNamespace = "http://server.messageboard/", wsdlLocation = "http://127.0.0.1:9999/messages?wsdl")
public class MessageBoardSOAPService
    extends Service
{

    private final static URL MESSAGEBOARDSOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException MESSAGEBOARDSOAPSERVICE_EXCEPTION;
    private final static QName MESSAGEBOARDSOAPSERVICE_QNAME = new QName("http://server.messageboard/", "MessageBoardSOAPService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:9999/messages?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MESSAGEBOARDSOAPSERVICE_WSDL_LOCATION = url;
        MESSAGEBOARDSOAPSERVICE_EXCEPTION = e;
    }

    public MessageBoardSOAPService() {
        super(__getWsdlLocation(), MESSAGEBOARDSOAPSERVICE_QNAME);
    }

    public MessageBoardSOAPService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MESSAGEBOARDSOAPSERVICE_QNAME, features);
    }

    public MessageBoardSOAPService(URL wsdlLocation) {
        super(wsdlLocation, MESSAGEBOARDSOAPSERVICE_QNAME);
    }

    public MessageBoardSOAPService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MESSAGEBOARDSOAPSERVICE_QNAME, features);
    }

    public MessageBoardSOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MessageBoardSOAPService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MessageBoardSOAP
     */
    @WebEndpoint(name = "MessageBoardSOAPPort")
    public MessageBoardSOAP getMessageBoardSOAPPort() {
        return super.getPort(new QName("http://server.messageboard/", "MessageBoardSOAPPort"), MessageBoardSOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MessageBoardSOAP
     */
    @WebEndpoint(name = "MessageBoardSOAPPort")
    public MessageBoardSOAP getMessageBoardSOAPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.messageboard/", "MessageBoardSOAPPort"), MessageBoardSOAP.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MESSAGEBOARDSOAPSERVICE_EXCEPTION!= null) {
            throw MESSAGEBOARDSOAPSERVICE_EXCEPTION;
        }
        return MESSAGEBOARDSOAPSERVICE_WSDL_LOCATION;
    }

}
