
package messageboard.client.jaxws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MessageBoardSOAP", targetNamespace = "http://server.messageboard/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MessageBoardSOAP {


    /**
     * 
     * @param arg0
     * @return
     *     returns messageboard.client.jaxws.Message
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMessage", targetNamespace = "http://server.messageboard/", className = "messageboard.client.jaxws.GetMessage")
    @ResponseWrapper(localName = "getMessageResponse", targetNamespace = "http://server.messageboard/", className = "messageboard.client.jaxws.GetMessageResponse")
    @Action(input = "http://server.messageboard/MessageBoardSOAP/getMessageRequest", output = "http://server.messageboard/MessageBoardSOAP/getMessageResponse")
    public Message getMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delete", targetNamespace = "http://server.messageboard/", className = "messageboard.client.jaxws.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://server.messageboard/", className = "messageboard.client.jaxws.DeleteResponse")
    @Action(input = "http://server.messageboard/MessageBoardSOAP/deleteRequest", output = "http://server.messageboard/MessageBoardSOAP/deleteResponse")
    public String delete(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws LengthExceededException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "create", targetNamespace = "http://server.messageboard/", className = "messageboard.client.jaxws.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://server.messageboard/", className = "messageboard.client.jaxws.CreateResponse")
    @Action(input = "http://server.messageboard/MessageBoardSOAP/createRequest", output = "http://server.messageboard/MessageBoardSOAP/createResponse", fault = {
        @FaultAction(className = LengthExceededException_Exception.class, value = "http://server.messageboard/MessageBoardSOAP/create/Fault/LengthExceededException")
    })
    public String create(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws LengthExceededException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<messageboard.client.jaxws.Message>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllMessagesFrom", targetNamespace = "http://server.messageboard/", className = "messageboard.client.jaxws.GetAllMessagesFrom")
    @ResponseWrapper(localName = "getAllMessagesFromResponse", targetNamespace = "http://server.messageboard/", className = "messageboard.client.jaxws.GetAllMessagesFromResponse")
    @Action(input = "http://server.messageboard/MessageBoardSOAP/getAllMessagesFromRequest", output = "http://server.messageboard/MessageBoardSOAP/getAllMessagesFromResponse")
    public List<Message> getAllMessagesFrom(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
