
package bank.client.jaxws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SimpleBankAccessService", targetNamespace = "http://local.bank/", wsdlLocation = "http://127.0.0.1:8888/bank?wsdl")
public class SimpleBankAccessService
    extends Service
{

    private final static URL SIMPLEBANKACCESSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIMPLEBANKACCESSSERVICE_EXCEPTION;
    private final static QName SIMPLEBANKACCESSSERVICE_QNAME = new QName("http://local.bank/", "SimpleBankAccessService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8888/bank?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIMPLEBANKACCESSSERVICE_WSDL_LOCATION = url;
        SIMPLEBANKACCESSSERVICE_EXCEPTION = e;
    }

    public SimpleBankAccessService() {
        super(__getWsdlLocation(), SIMPLEBANKACCESSSERVICE_QNAME);
    }

    public SimpleBankAccessService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIMPLEBANKACCESSSERVICE_QNAME, features);
    }

    public SimpleBankAccessService(URL wsdlLocation) {
        super(wsdlLocation, SIMPLEBANKACCESSSERVICE_QNAME);
    }

    public SimpleBankAccessService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIMPLEBANKACCESSSERVICE_QNAME, features);
    }

    public SimpleBankAccessService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SimpleBankAccessService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SimpleBankAccess
     */
    @WebEndpoint(name = "SimpleBankAccessPort")
    public SimpleBankAccess getSimpleBankAccessPort() {
        return super.getPort(new QName("http://local.bank/", "SimpleBankAccessPort"), SimpleBankAccess.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SimpleBankAccess
     */
    @WebEndpoint(name = "SimpleBankAccessPort")
    public SimpleBankAccess getSimpleBankAccessPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://local.bank/", "SimpleBankAccessPort"), SimpleBankAccess.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIMPLEBANKACCESSSERVICE_EXCEPTION!= null) {
            throw SIMPLEBANKACCESSSERVICE_EXCEPTION;
        }
        return SIMPLEBANKACCESSSERVICE_WSDL_LOCATION;
    }

}
