
package bank.client.jaxws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SimpleBankAccess", targetNamespace = "http://local.bank/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SimpleBankAccess {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws OverdrawException_Exception
     * @throws InactiveException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "transfer", targetNamespace = "http://local.bank/", className = "bank.client.jaxws.Transfer")
    @ResponseWrapper(localName = "transferResponse", targetNamespace = "http://local.bank/", className = "bank.client.jaxws.TransferResponse")
    @Action(input = "http://local.bank/SimpleBankAccess/transferRequest", output = "http://local.bank/SimpleBankAccess/transferResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://local.bank/SimpleBankAccess/transfer/Fault/IOException"),
        @FaultAction(className = OverdrawException_Exception.class, value = "http://local.bank/SimpleBankAccess/transfer/Fault/OverdrawException"),
        @FaultAction(className = InactiveException_Exception.class, value = "http://local.bank/SimpleBankAccess/transfer/Fault/InactiveException")
    })
    public void transfer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2)
        throws IOException_Exception, InactiveException_Exception, OverdrawException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNumber", targetNamespace = "http://local.bank/", className = "bank.client.jaxws.GetNumber")
    @ResponseWrapper(localName = "getNumberResponse", targetNamespace = "http://local.bank/", className = "bank.client.jaxws.GetNumberResponse")
    @Action(input = "http://local.bank/SimpleBankAccess/getNumberRequest", output = "http://local.bank/SimpleBankAccess/getNumberResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://local.bank/SimpleBankAccess/getNumber/Fault/IOException")
    })
    public String getNumber(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOwner", targetNamespace = "http://local.bank/", className = "bank.client.jaxws.GetOwner")
    @ResponseWrapper(localName = "getOwnerResponse", targetNamespace = "http://local.bank/", className = "bank.client.jaxws.GetOwnerResponse")
    @Action(input = "http://local.bank/SimpleBankAccess/getOwnerRequest", output = "http://local.bank/SimpleBankAccess/getOwnerResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://local.bank/SimpleBankAccess/getOwner/Fault/IOException")
    })
    public String getOwner(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createAccount", targetNamespace = "http://local.bank/", className = "bank.client.jaxws.CreateAccount")
    @ResponseWrapper(localName = "createAccountResponse", targetNamespace = "http://local.bank/", className = "bank.client.jaxws.CreateAccountResponse")
    @Action(input = "http://local.bank/SimpleBankAccess/createAccountRequest", output = "http://local.bank/SimpleBankAccess/createAccountResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://local.bank/SimpleBankAccess/createAccount/Fault/IOException")
    })
    public String createAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isActive", targetNamespace = "http://local.bank/", className = "bank.client.jaxws.IsActive")
    @ResponseWrapper(localName = "isActiveResponse", targetNamespace = "http://local.bank/", className = "bank.client.jaxws.IsActiveResponse")
    @Action(input = "http://local.bank/SimpleBankAccess/isActiveRequest", output = "http://local.bank/SimpleBankAccess/isActiveResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://local.bank/SimpleBankAccess/isActive/Fault/IOException")
    })
    public boolean isActive(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "closeAccount", targetNamespace = "http://local.bank/", className = "bank.client.jaxws.CloseAccount")
    @ResponseWrapper(localName = "closeAccountResponse", targetNamespace = "http://local.bank/", className = "bank.client.jaxws.CloseAccountResponse")
    @Action(input = "http://local.bank/SimpleBankAccess/closeAccountRequest", output = "http://local.bank/SimpleBankAccess/closeAccountResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://local.bank/SimpleBankAccess/closeAccount/Fault/IOException")
    })
    public boolean closeAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBalance", targetNamespace = "http://local.bank/", className = "bank.client.jaxws.GetBalance")
    @ResponseWrapper(localName = "getBalanceResponse", targetNamespace = "http://local.bank/", className = "bank.client.jaxws.GetBalanceResponse")
    @Action(input = "http://local.bank/SimpleBankAccess/getBalanceRequest", output = "http://local.bank/SimpleBankAccess/getBalanceResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://local.bank/SimpleBankAccess/getBalance/Fault/IOException")
    })
    public double getBalance(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws OverdrawException_Exception
     * @throws InactiveException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "withdraw", targetNamespace = "http://local.bank/", className = "bank.client.jaxws.Withdraw")
    @ResponseWrapper(localName = "withdrawResponse", targetNamespace = "http://local.bank/", className = "bank.client.jaxws.WithdrawResponse")
    @Action(input = "http://local.bank/SimpleBankAccess/withdrawRequest", output = "http://local.bank/SimpleBankAccess/withdrawResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://local.bank/SimpleBankAccess/withdraw/Fault/IOException"),
        @FaultAction(className = OverdrawException_Exception.class, value = "http://local.bank/SimpleBankAccess/withdraw/Fault/OverdrawException"),
        @FaultAction(className = InactiveException_Exception.class, value = "http://local.bank/SimpleBankAccess/withdraw/Fault/InactiveException")
    })
    public void withdraw(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1)
        throws IOException_Exception, InactiveException_Exception, OverdrawException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws InactiveException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deposit", targetNamespace = "http://local.bank/", className = "bank.client.jaxws.Deposit")
    @ResponseWrapper(localName = "depositResponse", targetNamespace = "http://local.bank/", className = "bank.client.jaxws.DepositResponse")
    @Action(input = "http://local.bank/SimpleBankAccess/depositRequest", output = "http://local.bank/SimpleBankAccess/depositResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://local.bank/SimpleBankAccess/deposit/Fault/IOException"),
        @FaultAction(className = InactiveException_Exception.class, value = "http://local.bank/SimpleBankAccess/deposit/Fault/InactiveException")
    })
    public void deposit(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1)
        throws IOException_Exception, InactiveException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccountNumbers", targetNamespace = "http://local.bank/", className = "bank.client.jaxws.GetAccountNumbers")
    @ResponseWrapper(localName = "getAccountNumbersResponse", targetNamespace = "http://local.bank/", className = "bank.client.jaxws.GetAccountNumbersResponse")
    @Action(input = "http://local.bank/SimpleBankAccess/getAccountNumbersRequest", output = "http://local.bank/SimpleBankAccess/getAccountNumbersResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://local.bank/SimpleBankAccess/getAccountNumbers/Fault/IOException")
    })
    public List<String> getAccountNumbers()
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "accountExists", targetNamespace = "http://local.bank/", className = "bank.client.jaxws.AccountExists")
    @ResponseWrapper(localName = "accountExistsResponse", targetNamespace = "http://local.bank/", className = "bank.client.jaxws.AccountExistsResponse")
    @Action(input = "http://local.bank/SimpleBankAccess/accountExistsRequest", output = "http://local.bank/SimpleBankAccess/accountExistsResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://local.bank/SimpleBankAccess/accountExists/Fault/IOException")
    })
    public boolean accountExists(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws IOException_Exception
    ;

}
